#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/CameraPlugIns/"

cp "/tmp/SBIG_Aluma_X2/cameralist SBIG_Aluma.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SBIG_CamSelect.ui"
cp "/tmp/SBIG_Aluma_X2/SBIG_CamSelect.ui" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SBIG_AlumaCamera.ui"
cp "/tmp/SBIG_Aluma_X2/SBIG_AlumaCamera.ui" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/SBIG_Aluma.png"
cp "/tmp/SBIG_Aluma_X2/SBIG_Aluma.png" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/CameraPlugIns/libSBIG_Aluma.dylib"
cp "/tmp/SBIG_Aluma_X2/libSBIG_Aluma.dylib" "$PLUGINS_DIR/CameraPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "/usr/local/lib/libftd2xx.dylib"
cp -f "/tmp/SBIG_Aluma_X2/libftd2xx.dylib" "/usr/local/lib/libftd2xx.dylib"
chmod 755 "/usr/local/lib/libftd2xx.dylib"

rm -f "/usr/local/lib/libftd3xx.dylib"
cp -f "/tmp/SBIG_Aluma_X2/libftd3xx.dylib" "/usr/local/lib/libftd3xx.dylib"
chmod 755 "/usr/local/lib/libftd3xx.dylib"


app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/cameralist SBIG_Aluma.txt"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SBIG_CamSelect.ui"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SBIG_AlumaCamera.ui"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/SBIG_Aluma.png"
	chown $app_owner "$PLUGINS_DIR/CameraPlugIns/libSBIG_Aluma.dylib"
fi

rm -rf /tmp/SBIG_Aluma_X2

